server:
  port: 8081
spring:
  application:
    name: graphql-service
  graphql:
    graphiql:
      enabled: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
